### ISSUE TITLE
多语言切换时的链接有点问题。

### ISSUE THREAD

**Issue by gudufy** [yeesoft/yii2-multilingual#1]
非常感谢作者能提供这么方便的扩展，我在整合YII2的过程中发现一点问题。以下是我修改后的代码，希望你能够修正。
source(views/pill.php line 22):
`<?= Html::a($title, ArrayHelper::merge($params, [$url, "language" => $key, "forceLanguageParam" => true])) ?>`

changed:
`<?= Html::a($title, Yii::$app->urlManager->createUrl(ArrayHelper::merge($params, [$url, "language" => $key]))) ?>`

**Comment by yeesoft** [comment]
Fixed.
